services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: |
      # تثبيت Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      
      # تهيئة conda
      $HOME/miniconda/bin/conda init bash
      source $HOME/.bashrc
      $HOME/miniconda/bin/conda config --add channels conda-forge
      
      # إنشاء وتفعيل بيئة conda
      $HOME/miniconda/bin/conda create -n myenv python=3.11 -y
      source $HOME/miniconda/bin/activate myenv
      
      # تثبيت TA-Lib وباقي المتطلبات
      $HOME/miniconda/bin/conda install -c conda-forge ta-lib -y
      pip install -r requirements.txt
    startCommand: |
      source $HOME/miniconda/bin/activate myenv
      gunicorn main:server --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PATH
        value: $HOME/miniconda/bin:$PATH
