services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: |
      # تثبيت المكتبات الأساسية المطلوبة
      apt-get update
      apt-get install -y build-essential wget

      # تحميل وتثبيت TA-Lib
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xvf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure --prefix=/usr
      make
      make install
      cd ..
      rm -rf ta-lib-0.4.0-src.tar.gz ta-lib/
      
      # تثبيت المتطلبات
      pip install -r requirements.txt
    startCommand: gunicorn main:server --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/lib
