services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
